<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatalogItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'name'        => 'Warung Bu Tini',
                'category'    => 'Culinary',
                'price'       => 10000,
                'price_label' => '/porsi',
                'image'       => null,
                'short_desc'  => 'Nasi rames legendaris dekat kampus Unimus.',
                'description' => 'Warung sederhana dengan menu nasi rames, ayam goreng, sayur lodeh, dan tempe bacem. Porsi mahasiswa, harga ramah dompet.',
                'facilities'  => json_encode(['Dine-in','Take away','Free wifi','Toilet']),
                'hours'       => '07.00 – 21.00 (Senin–Sabtu)',
                'contact'     => '0812-3456-7890',
                'address'     => 'Jl. Kedungmundu Raya No.18, Semarang',
                'lat'         => -7.0234,
                'lng'         => 110.4621,
                'instagram'   => 'warungbutini',
                'tiktok'      => 'warungbutini',
            ],
            [
                'name'        => 'Mie Ayam Pak Slamet',
                'category'    => 'Culinary',
                'price'       => 12000,
                'price_label' => '/mangkok',
                'image'       => null,
                'short_desc'  => 'Mie ayam bakso favorit anak Unimus.',
                'description' => 'Mie ayam dengan kuah kaldu gurih, topping ayam kecap, bakso sapi, dan pangsit goreng renyah.',
                'facilities'  => json_encode(['Dine-in','Take away','Parkir luas']),
                'hours'       => '10.00 – 22.00 (setiap hari)',
                'contact'     => '0856-1122-3344',
                'address'     => 'Jl. Sambiroto No.5, Tembalang',
                'lat'         => -7.0451,
                'lng'         => 110.4502,
                'instagram'   => 'mieayampakslamet',
            ],
            [
                'name'        => 'Ayam Geprek Juara',
                'category'    => 'Culinary',
                'price'       => 15000,
                'price_label' => '/paket',
                'image'       => null,
                'short_desc'  => 'Geprek pedas level 1–10 + nasi + es teh.',
                'description' => 'Paket hemat mahasiswa: ayam geprek, nasi, lalapan, sambal bawang, dan es teh manis.',
                'facilities'  => json_encode(['Dine-in','GoFood','GrabFood','Wifi']),
                'hours'       => '10.00 – 23.00',
                'contact'     => '0877-9988-7766',
                'address'     => 'Jl. Kedungmundu Raya No.40',
                'lat'         => -7.0241,
                'lng'         => 110.4639,
                'instagram'   => 'ayamgeprekjuara',
                'tiktok'      => 'geprekjuara',
            ],
            [
                'name'        => 'Kost Melati Putri',
                'category'    => 'Kost',
                'price'       => 750000,
                'price_label' => '/bulan',
                'image'       => null,
                'short_desc'  => 'Kost putri 5 menit jalan kaki ke kampus.',
                'description' => 'Kost putri dengan kamar mandi dalam, kasur, lemari, dan meja belajar. Lingkungan aman dengan ibu kost yang ramah.',
                'facilities'  => json_encode(['KM dalam','Wifi 50Mbps','Dapur bersama','Parkir motor','CCTV']),
                'hours'       => 'Survey: 09.00 – 17.00',
                'contact'     => '0813-2200-1100',
                'address'     => 'Jl. Kedungmundu Gg. Melati No.7',
                'lat'         => -7.0220,
                'lng'         => 110.4610,
                'instagram'   => 'kostmelatiunimus',
            ],
            [
                'name'        => 'Kost Aulia Putra',
                'category'    => 'Kost',
                'price'       => 600000,
                'price_label' => '/bulan',
                'image'       => null,
                'short_desc'  => 'Kost putra ekonomis, dekat warung & laundry.',
                'description' => 'Kamar standar dengan KM luar, listrik token, dan akses 24 jam. Cocok untuk mahasiswa rantau.',
                'facilities'  => json_encode(['KM luar','Wifi','Parkir motor','Akses 24 jam']),
                'hours'       => 'Survey kapan saja (WA dulu)',
                'contact'     => '0822-7788-9900',
                'address'     => 'Jl. Sambiroto Raya No.21',
                'lat'         => -7.0445,
                'lng'         => 110.4488,
            ],
            [
                'name'        => 'Griya Asri Eksklusif',
                'category'    => 'Kost',
                'price'       => 1200000,
                'price_label' => '/bulan',
                'image'       => null,
                'short_desc'  => 'Kost premium dengan AC & water heater.',
                'description' => 'Kamar luas dengan AC, water heater, smart TV, dan sarapan setiap pagi. Lingkungan tenang dan asri.',
                'facilities'  => json_encode(['AC','Water heater','Sarapan','Wifi 100Mbps','Laundry']),
                'hours'       => 'Survey: 08.00 – 20.00',
                'contact'     => '0811-3344-5566',
                'address'     => 'Jl. Tunjung Sari No.10',
                'lat'         => -7.0205,
                'lng'         => 110.4585,
                'instagram'   => 'griyaasrismg',
            ],
            [
                'name'        => 'BRT Koridor II — Terboyo ↔ Sisemut',
                'category'    => 'BRT',
                'price'       => 3500,
                'price_label' => '/trip (umum)',
                'image'       => null,
                'short_desc'  => 'Lewat kawasan kampus Unimus Kedungmundu.',
                'description' => 'Koridor II Trans Semarang melayani rute Terboyo – Sisemut, melewati Jl. Kedungmundu dan dekat dengan kampus Unimus.',
                'facilities'  => json_encode(['AC','Tap kartu','Tarif pelajar Rp1.000','Headway ±10 menit']),
                'hours'       => '05.30 – 18.00 (setiap hari)',
                'contact'     => 'Call center 1500-928',
                'address'     => 'Halte Kedungmundu',
                'lat'         => -7.0238,
                'lng'         => 110.4625,
                'route_code'  => 'K2',
                'stops'       => json_encode(['Terboyo','Pengapon','Bubakan','Mataram','Kedungmundu (Unimus)','Meteseh','Sisemut Ungaran']),
            ],
            [
                'name'        => 'BRT Koridor I — Mangkang ↔ Penggaron',
                'category'    => 'BRT',
                'price'       => 3500,
                'price_label' => '/trip (umum)',
                'image'       => null,
                'short_desc'  => 'Koridor utama lintas barat–timur Semarang.',
                'description' => 'Koridor I melayani Mangkang – Penggaron, transit ke koridor lain via Simpang Lima dan Balaikota.',
                'facilities'  => json_encode(['AC','Tap kartu','Tarif pelajar Rp1.000']),
                'hours'       => '05.30 – 18.00',
                'contact'     => 'Call center 1500-928',
                'address'     => 'Halte Balaikota (transit)',
                'lat'         => -6.9900,
                'lng'         => 110.4200,
                'route_code'  => 'K1',
                'stops'       => json_encode(['Mangkang','Karang Ayu','Tugu Muda','Balaikota','Milo','Penggaron']),
            ],
        ];

        DB::table('catalog_items')->insert($items);
    }
}   